apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/tidy-amplifier-477616-d8/locations/asia-south1/clusters/gs-cluster-2

